//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClotheStore.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class clothe
    {
        public int id { get; set; }
        public string name { get; set; }
        public string size { get; set; }
        public string color { get; set; }
        public string brand { get; set; }
        public string url { get; set; }
        public byte[] image { get; set; }
    }
}
